import Head from 'next/head'
import Registration from './Registration'

export default function Home() {
  return (
    <div className='bg-green-300 h-screen ' >
      <Head>
        <title>Next.Js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Registration/>
    </div>
  )
}

